name: local-duplicate-finder
services:
  local-duplicate-finder:
    container_name: local-duplicate-finder
    hostname: local-duplicate-finder
    restart: unless-stopped
    ports:
      - 8501:8501
    build:
      dockerfile: './Dockerfile'
    volumes:
      # Mount your local pictures folder into the container
      # - /path/to/your/pictures:/pictures
      # Mount a local folder to persist the database and index files
      - ./data:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # or 'all' to use all available GPUs
              capabilities: [gpu]
